### PR TITLE
increase default fetch limits.

### PR DESCRIPTION
**Pull request by zburke**
Surely this is wrong, and yet I'm not sure what the right approach would
be. This is a select list so we certainly don't want paging here; we want _all_ the values.

Refs [UIORG-61](https://issues.folio.org/browse/UIORG-61), [UIORG-65](https://issues.folio.org/browse/UIORG-65).

### CODE REVIEW

**Comment by MikeTaylor** [comment]
Very nasty race-condition in GitHub's UI. Here. I wrote a long, interesting comment on why this _is_ the right solution, and submitted it as an "Approve" review. But GitHub rejected it: "you can only approve unmerged PRs" -- and _discarded my comment_ instead of downgrading it from an "Approve" review to a regular comment. That's just broken.

**Comment by MikeTaylor** [comment]
Anyway: this fix is good.

**Comment by zburke** [comment]
But if I want _all_ the rows, there needs to be a parameter I can pass that indicates "all the rows", not 
"up to 100 rows, which hopefully is all of them, but might not be".

**Comment by zburke** [comment]
Also, that _is_ a nasty bug. Did you file a report at https://github.com/contact?

**Comment by MikeTaylor** [comment]
I did not. It's too late, my comment is gone.

But _if_ it was here, you would see immediately that your fix _is_ correct.

**Comment by skomorokh** [comment]
Aaaactually it's best not to put query parameters onto the `path` like that as that part of the path is managed by `params` property which'll do the urlencoding and &ing for you. No big deal here because you're not using `params` (or `records` which would be even more apropos) but it's best practice to use those as someone might come along later and add such a property which may get weird.

**Pull request merged**
