### PR TITLE
UIORG-40 adding okapi Url input

### PR DESCRIPTION
**Pull request by magicmamaliga**

### CODE REVIEW

**Comment by mkuklis** [comment]
@magicmamaliga is this still a valid PR? It was created 11 days ago. Please let me know so we can merge it in.

**Comment by magicmamaliga** [comment]
Hello,
Yes, you can merge it.

Mate Tornai

Ps.: I am in Qulto developer team.



2018. jan. 30. du. 3:05 ezt írta ("Michał Kuklis" <notifications@github.com
>):

@magicmamaliga <https://github.com/magicmamaliga> is this still a valid PR?
It was created 11 days ago. Please let me know so we can merge it in.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/folio-org/ui-organization/pull/27#issuecomment-361602643>,
or mute the thread

**Comment by mkuklis** [comment]
@magicmamaliga sounds good. In the future would you mind adding somebody to review the PR? Otherwise it's hard to know when something is ready. Thanks!

**Comment by magicmamaliga** [comment]
I think so. This was my very first git pull request.


2018. jan. 30. du. 3:23 ezt írta ("Michał Kuklis" <notifications@github.com

**Pull request merged**
