### PR TITLE
UIORG-37 Update login-saml interface name

### PR DESCRIPTION
**Pull request by szkata**
@wafschneider we released the Login SAML module and updated the interface declaration so I changed the reference in the package.json. Could you check and merge my PR if it is okay?

### CODE REVIEW

**Comment by szkata** [comment]
Yes, the interface name has changed. Link for the PR changes: 
https://github.com/folio-org/mod-login-saml/pull/16/files

**Comment by MikeTaylor** [comment]
Yep, this is fine. Go ahead and merge!

**Comment by szkata** [comment]
@MikeTaylor could you merge it? I do not have permission to do that.

**Comment by MikeTaylor** [comment]
Sure!

**Pull request merged**
